### ISSUE TITLE
Not working with the new CLI

### ISSUE THREAD

**Issue by TylerJPresley** [miguelzakharia/aurelia-google-analytics#10]
I've got a CLI project that I converted from JSPM/ES6. After the upgrade I noticed that I was getting some unhelpful errors with this plugin. During the build process this is all I get.

**CLI build process**

```
Tracing aurelia-google-analytics...
error /Users/.../node_modules/aurelia-google-analytics/dist/amd/aurelia-google-analytics.js
```

**Chrome console**

```
Uncaught TypeError: Cannot read property '__useDefault' of undefined
ensureOriginOnExports @ aurelia.js:14791
(anonymous function) @ aurelia.js:14899
execCb @ aurelia.js:5347
check @ aurelia.js:4535
enable @ aurelia.js:4827
init @ aurelia.js:4440
(anonymous function) @ aurelia.js:5111
```

**Comment by TylerJPresley** [comment]
Looks like the default plugin way is for the configure to be in the analytics file not the index. Why I was confused.

```
          {
            "name": "aurelia-google-analytics",
            "path": "../node_modules/aurelia-google-analytics/dist/amd",
            "main": "index"
          },
```

**Comment by miguelzakharia** [comment]
Sorry for the delayed response. I just got back from vacation late last night. Is it working for you after that change?
