### ISSUE TITLE
Custom attribute for event-value

### ISSUE THREAD

**Issue by Senseye** [miguelzakharia/aurelia-google-analytics#11]
Is it possible to add a similar data attribute for value?

data-analytics-value.

Currently it's missing.

Thanks.

**Comment by miguelzakharia** [comment]
@Senseye I just published v2.0.0 which adds `data-analytics-value`. I'm going to close this issue. If you have any problems, please feel free to open a new issue. Thanks!

**Comment by Senseye** [comment]
@miguelzakharia thanks a lot!
