### ISSUE TITLE
gulp build complains about missing "conventional-changeset"

### ISSUE THREAD

**Issue by ostyn** [miguelzakharia/aurelia-google-analytics#13]
Couldn't build without doing this first. Adding case to PR against.

**Comment by ostyn** [comment]
Hmmm... I thought the PR would auto-link against this by adding #13 at the front of the commit. My mistake. 
Anyway, PR in #14

**Comment by miguelzakharia** [comment]
I think you need to add a keyword in the commit message such as "Fix" or "Fixes" and then the Issue ID. Odd that it wouldn't build without that dependency, but oh well. I'll merge this.
