### ISSUE TITLE
Ignore route

### ISSUE THREAD

**Issue by damylen** [miguelzakharia/aurelia-google-analytics#23]
Is it possible to ignore a specific route to be included in the analysis? Some of my pages are be called by a bot (on purpose) and I would like those pages to be removed from google analytics.

**Comment by miguelzakharia** [comment]
Currently there is not. However, `pageTracking` option can be modified to include an `ignore` property. Maybe it can take a regex that is checked before the tracking info is sent to GA. Would that work?
