### ISSUE TITLE
Tracking doesn't take into account the root path

### ISSUE THREAD

**Issue by bmarotta** [miguelzakharia/aurelia-google-analytics#24]
Hi Miguel,

First of all, your plugin looks great. Nevertheless the tracking doesn't take into account the path where the aurelia is running. For instance, if I have a host www.myhost.com and the aurelia website is running under the path mysite:

www.myhost.com/mysite

When I navigate to home the tracked page is /home and not /mysite/home. Any ideas how to overcome this? If not it would be site if one could configure the host path to be prefixed to the message sent.

Cheers,

**Comment by miguelzakharia** [comment]
Hi @bmarotta, 

That's an interesting problem. I think the full path/host is available on the router, but I have not looked into it before. I might have time this week to do some research. Adding a config option would be easy, however I would prefer not to if it can be avoided.

**Comment by miguelzakharia** [comment]
I just published v2.3.0 to NPM. It contains a way to override where the URL comes from. I updated the README to reflect how to override the function.

**Comment by bmarotta** [comment]
great news. I'm currently on vacations. I will check on Monday 

⁣Bruno Marotta​

**Comment by bmarotta** [comment]
Hi Miguel,

It worked fine. To make it look really clean I had to remove the 
hostname. Also I made it in a way so that the route path (everything 
after #) is part of the url too. The final code is:

getUrl: (payload) => {
                   return 
window.location.href.replace(/^[a-zA-Z]{3,5}\:\/{2}[a-zA-Z0-9_.:-]+\//, 
'').replace("/#/", "/").replace("/#", "/");
               }
