### ISSUE TITLE
Error on loading module when used with Typescript

### ISSUE THREAD

**Issue by maroy1986** [miguelzakharia/aurelia-google-analytics#3]
Hi there,

The plugin simply just not load at all when used with Typescript. Here's a screenshot of the error  
![image](https://cloud.githubusercontent.com/assets/2490360/12966992/a3ce7b8e-d030-11e5-810b-5442e4c9782f.png)

To help find the problem, I've made a repo where you can easily reproduce the issue simply by running the gulp watch command : 
https://github.com/maroy1986/demo-aurelia-google-analytics-typescript/tree/master/src

I will continu to investigate on my side and report if I find anything.

Thanks!

**Comment by maroy1986** [comment]
I just founded that replacing the file included in the jspm package, which are the ES6 version, by the AMD version, makes everything works, That said, I've seen that most of the other package use AMD modules in their package. I'm not sure this is the best way to solve the issue, but a least this is a starting point.

**Comment by miguelzakharia** [comment]
In that case, version 1.0.3 should work. There was a recent pull request that set it to AMD by default instead of ES6.

**Comment by maroy1986** [comment]
That's exactly what I found here last night when I looked at the dist folder in your repo. As I said, I manually replaced the files in jspm_packages folder of your plugin and everything start to work. So yeah, 1.0.3 should work right of the box. Have you any timeline on the release of this update? 

Thanks for you time!

**Comment by droda59** [comment]
I think it's already out, released 6 days ago

**Comment by miguelzakharia** [comment]
It was released a few days ago.

**Comment by maroy1986** [comment]
Actually it doesn't look to work : 
![image](https://cloud.githubusercontent.com/assets/2490360/12979270/055e8af6-d0a4-11e5-84de-f995e65c1492.png)

**Comment by miguelzakharia** [comment]
Odd, I'll look into it today.

**Comment by maroy1986** [comment]
I think you just need to create a new Release in your repo, which will create a tag on 1.0.3 and hence, make it work properly ;)

**Comment by miguelzakharia** [comment]
I just remembered that as well! Thanks for your patience, I'm learning this
stuff as I go. :) I just published the release, so check to make sure an
update works for you. If so, this issue can be closed.

**Comment by maroy1986** [comment]
No problem! I really appreciate your fast response and support! I confirm that it is now working properly when updating from JSPM and it is working when I execute the typescript skeleton.

I'll update the dependency in our application tonight as i'm at work at the moment but for me, this issue can now be closed :) 

Thanks again for everything!
