### ISSUE TITLE
multiple router:navigation:complete events

### ISSUE THREAD

**Issue by flieks** [miguelzakharia/aurelia-google-analytics#4]
Hi,

thanks for the plugin.

1 problem i have 
I already have a listener for router:navigation:complete in my app.ts.
It seems to override the subscriber in your plugin so it never gets called. Ok this is more of an aurelia problem but how can we solve it?

Thanks
Felix

**Comment by miguelzakharia** [comment]
Hi Felix,

I'm not really sure what the solution is. I'll have to research a little.
It might have something to do with the way the event subscription is set
up. I'll spend some time on it during this week. In the meantime, it might
be worth checking in the Gitter Aurelia channel to see if anyone has
already come across this.

**Comment by flieks** [comment]
i searched gitter but there is no solution there.
i placed new [issue ](https://github.com/aurelia/router/issues/310) at aurelia

got it to work but had to add the Analytics to the window in your plugin code..
thanks for help

**Comment by miguelzakharia** [comment]
Since it seems to be an Aurelia framework issue, I'm going to close this one. Let me know if it needs to be reopened.
