### ISSUE TITLE
in-page

### ISSUE THREAD

**Issue by flieks** [miguelzakharia/aurelia-google-analytics#5]
Hi,

In analytics it complains when i want to see the in-page stats. It says the ga or analytics.js is not on the page

Thanks
Felix

**Comment by miguelzakharia** [comment]
Thanks for reporting this. I also experience the same issue when checking In-Page Analytics under the Behavior category. I followed the suggestion that was displayed in the message which said to install the Chrome extension. Opening the site with the extension displayed the stats. Will this solution work for you?

![image](https://cloud.githubusercontent.com/assets/682476/13852836/60d599e0-ec3a-11e5-8bd4-096b40a4f0de.png)
