### ISSUE TITLE
Tracking onChange events

### ISSUE THREAD

**Issue by SorenMuller** [miguelzakharia/aurelia-google-analytics#9]
Hi,
How do I track Onchange events on a select element ?

**Comment by SorenMuller** [comment]
And how to access ga runtime from js.. ??

**Comment by miguelzakharia** [comment]
Hi, `ga` is on the`window` object. Regarding onChange, there currently is no support for that. So far only page navigation and click events are supported.

**Comment by miguelzakharia** [comment]
I'm going to close this for now. Please let me know if you would like to reopen it for any reason.
